openapi: 3.0.2

info:
  title: Microservice Blank API #todo replace!
  description: Blank for feather project (Need to be replaced) #todo replace!
  version: 1.0.0
  contact:
    name: Andrew Belunov
    email: cyberpunk.perosn@gmail.com

tags:
  - name: tests
    description: blank description

paths:

  /tests:

    get:
      tags:
        - tests
      summary: getTests
      description: Get tests response
      operationId: getTests
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTestsResponse'
        400:
          $ref: 'common/components/responses/Error.yaml'
        401:
          $ref: 'common/components/responses/Error.yaml'
        500:
          $ref: 'common/components/responses/Error.yaml'

components:

  schemas:

    GetTestsResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          description: List of existing items
          type: string