spring:
  application:
    name: microservice-blank #todo replace!

server:
  servlet:
    context-path: /blank #todo replace
  openapi:
    enabled: false

logging:
  level:
    root: info
    org.springframework.boot.web.servlet: trace
    com.github.cyberpunkperson: debug #todo replace!
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X] %logger{80} %msg%n'